"""Single user-adjustable configuration source for pyDHT."""
from __future__ import annotations

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DB_DIR = BASE_DIR / "db"
SQLITE_PATH = DB_DIR / "pydht.sqlite3"
DHT_NETWORK_JSONL_PATH = DB_DIR / "dht_network.jsonl"
DHT_ROUTING_JSONL_PATH = DB_DIR / "dht_routing.jsonl"

# DHT
DHT_BIND_HOST = "0.0.0.0"
DHT_BIND_PORT = 6881
DHT_BOOTSTRAP_NODES = (
    ("router.bittorrent.com", 6881),
    ("router.utorrent.com", 6881),
    ("dht.transmissionbt.com", 6881),
)
DHT_CLIENT_VERSION = "qB7K"
DHT_MAX_REQUESTS_PER_SECOND = 50
DHT_QUERY_BURST = 10
DHT_MAX_PENDING_REQUESTS = 200
DHT_QUERY_TIMEOUT = 5.0
DHT_LOOKUP_PARALLELISM = 3
DHT_LOOKUP_DEADLINE = 15.0
MAX_DHT_QUERIES_PER_TORRENT = 100
DHT_READ_ONLY = False
ALLOW_NON_GLOBAL_ENDPOINTS = False
DHT_RECEIVE_MAX_BYTES = 64 * 1024
DHT_ROUTING_GOOD_TTL = 15 * 60
DHT_ROUTING_BAD_AFTER_FAILURES = 2
DHT_ROUTING_REFRESH_INTERVAL = 15 * 60
DHT_MAINTENANCE_INTERVAL = 30.0
DHT_BOOTSTRAP_RETRY_INTERVAL = 60.0

# Torrent processing
HASH_QUEUE_SIZE = 5000
MAX_ACTIVE_TORRENTS = 32
MAX_PEER_HINTS_PER_CANDIDATE = 4
RECENT_HASH_CACHE_SIZE = 100_000
RECENT_HASH_TTL = 3600
MAX_METADATA_ATTEMPTS_PER_TORRENT = 20

# Peer sessions
MAX_PEER_CONNECTIONS = 32
MAX_PEERS_PER_TORRENT = 20
PEER_CONNECT_TIMEOUT = 5.0
PEER_HANDSHAKE_TIMEOUT = 5.0
PEER_SESSION_TIMEOUT = 30.0
METADATA_TIMEOUT = 15.0
METADATA_REQUEST_PIPELINE = 4
MAX_METADATA_SIZE = 4 * 1024 * 1024
MAX_PEER_MESSAGE_SIZE = 4 * 1024 * 1024 + 64 * 1024
PEER_CLIENT_NAME = "pyDHT/0.1"
PEER_ID_PREFIX = "-PD0100-"  # 8 bytes; remaining 12 bytes are random per process.

# Bencode / torrent parser limits
MAX_BENCODE_DEPTH = 64
MAX_BENCODE_ITEMS = 200_000
MAX_BENCODE_STRING_LENGTH = 4 * 1024 * 1024
MAX_FILES_PER_TORRENT = 100_000
MAX_PATH_COMPONENTS = 128
MAX_INDEX_TEXT_LENGTH = 16 * 1024
MAX_EVIDENCE_TEXT_LENGTH = 4096

# BEP-51
DHT_BEP51_ENABLED = True
DHT_BEP51_GLOBAL_INTERVAL = 1.0
DHT_BEP51_RESPONSE_INTERVAL = 300
DHT_BEP51_UNSUPPORTED_BACKOFF = 3600
BEP51_QUEUE_HIGH_WATERMARK = 0.80
BEP51_QUEUE_LOW_WATERMARK = 0.30
BEP51_NODE_STATE_MAX = 10_000
BEP51_NODE_STATE_TTL = 3600
BEP51_MAX_SAMPLES_PER_RESPONSE = 50

# DHT peer store
DHT_PEER_STORE_MAX_INFOHASHES = 10_000
DHT_PEER_STORE_MAX_PEERS_PER_HASH = 50
DHT_PEER_STORE_TTL = 1800

# Tokens
DHT_TOKEN_ROTATION_INTERVAL = 300
DHT_TOKEN_VALIDITY = 600

# SQLite
DB_QUEUE_SIZE = 64
DB_BUSY_TIMEOUT = 5.0
DB_WAL_ENABLED = True
DB_SYNCHRONOUS = "NORMAL"
DATABASE_MAX_BYTES = 20 * 1024 * 1024 * 1024
RAW_INFO_STORAGE = "zlib"  # off | raw | zlib
DB_REOPEN_RETRY_COUNT = 5
DB_REOPEN_RETRY_DELAY = 2.0

# Retry scheduler
RETRY_SCAN_INTERVAL = 60
RETRY_SCAN_BATCH_SIZE = 32
FETCH_RETRY_BASE_SECONDS = 60
FETCH_RETRY_MAX_SECONDS = 6 * 3600
FETCH_RETRY_MAX_ATTEMPTS = 20

# JSONL
DHT_JSONL_QUEUE_SIZE = 5000
DHT_JSONL_FLUSH_INTERVAL = 1.0
DHT_JSONL_MAX_BYTES = 512 * 1024 * 1024
DHT_JSONL_BACKUP_COUNT = 4
JSONL_REOPEN_RETRY_COUNT = 5
JSONL_REOPEN_RETRY_DELAY = 2.0
DEBUG_FULL_KRPC_JSONL = False
JSONL_WARNING_INTERVAL = 60.0

# Monitoring
KEYWORD_MONITORING_ENABLED = False
KEYWORDS = ()
KEYWORD_CASE_SENSITIVE = False

# Telegram
TELEGRAM_ENABLED = False
TELEGRAM_BOT_TOKEN = os.environ.get("PYDHT_TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("PYDHT_TELEGRAM_CHAT_ID", "")
TELEGRAM_HTTP_TIMEOUT = 10.0
TELEGRAM_MESSAGE_MAX_CHARS = 4096
TELEGRAM_HTTP_MAX_RESPONSE_BYTES = 1024 * 1024
TELEGRAM_MAX_MATCH_LINES = 20
NOTIFICATION_RETRY_BASE_SECONDS = 60
NOTIFICATION_RETRY_MAX_SECONDS = 6 * 3600
NOTIFICATION_RETRY_MAX_ATTEMPTS = 20
NOTIFICATION_SCAN_INTERVAL = 30
NOTIFICATION_SCAN_BATCH_SIZE = 16

# Search
SEARCH_RESULT_LIMIT = 100

# Logging
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s %(levelname)s %(name)s %(message)s"
